### ISSUE TITLE
Translating some netcdf files raise a JSON not serializable then if recovered segfault/double free

### ISSUE THREAD

**Issue by gbfree** [fsspec/kerchunk#172]
Translating some netcdf files with kerchunk raise TypeError: Object of type bytes is not JSON serializable. If the exception is caught the application then segfault or double free.

Made a small reproducible exemple using the failling netcdf file in this archive: [viscal.zip](https://github.com/fsspec/kerchunk/files/8876841/viscal.zip)

The netcdf doesn't deems to be corrupted as it can be read with ncdump (it's header is in annex).

### Code exemple
```python
import traceback
import fsspec
import kerchunk.hdf


def my_kerchunk_context(open_file, url):
    try:
        kerchunk_info = kerchunk.hdf.SingleHdf5ToZarr(open_file, url)
        print("SingleHdf5ToZarr done. Start translate.")
        zarr_compatible_data = kerchunk_info.translate()
        print("Success with", url)
    except Exception as err:
        print("Fail with exception", url)
        print(err)
        print(traceback.format_exc())


def my_fsspec_context(url):
    with fsspec.open(url, "rb") as open_file:
        my_kerchunk_context(open_file, url)

folder = "/home/gbeaucha/CSC-DPR/eopf-cpm/data/S3A_SL_1_RBT____20220603T234543_20220603T234843_20220605T083021_0179_086_087_3780_PS1_O_NT_004.SEN3/"
bad_file = "viscal.nc"

my_fsspec_context(folder+bad_file)
print("Exited all contexts")

```
## Console output

```
SingleHdf5ToZarr done. Start translate.

/home/gbeaucha/.local/share/virtualenvs/eopf-cpm-gah88zwo/lib/python3.9/site-packages/zarr/storage.py:432: FutureWarning: missing object_codec for object array; this will raise a ValueError in version 3.0

  warnings.warn('missing object_codec for object array; this will raise a '

Fail with exception /home/gbeaucha/CSC-DPR/eopf-cpm/data/S3A_SL_1_RBT____20220603T234543_20220603T234843_20220605T083021_0179_086_087_3780_PS1_O_NT_004.SEN3/viscal.nc

Object of type bytes is not JSON serializable

Traceback (most recent call last):

  File "/home/gbeaucha/CSC-DPR/eopf-cpm/kerchunk_issue.py", line 12, in my_kerchunk_context

    zarr_compatible_data = kerchunk_info.translate()

  File "/home/gbeaucha/.local/share/virtualenvs/eopf-cpm-gah88zwo/lib/python3.9/site-packages/kerchunk/hdf.py", line 73, in translate

    self._h5f.visititems(self._translator)

  File "/home/gbeaucha/.local/share/virtualenvs/eopf-cpm-gah88zwo/lib/python3.9/site-packages/h5py/_hl/group.py", line 613, in visititems

    return h5o.visit(self.id, proxy)

  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper

  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper

  File "h5py/h5o.pyx", line 355, in h5py.h5o.visit

  File "h5py/h5o.pyx", line 302, in h5py.h5o.cb_obj_simple

  File "/home/gbeaucha/.local/share/virtualenvs/eopf-cpm-gah88zwo/lib/python3.9/site-packages/h5py/_hl/group.py", line 612, in proxy

    return func(name, self[name])

  File "/home/gbeaucha/.local/share/virtualenvs/eopf-cpm-gah88zwo/lib/python3.9/site-packages/kerchunk/hdf.py", line 190, in _translator

    za = self._zroot.create_dataset(h5obj.name, shape=h5obj.shape,

  File "/home/gbeaucha/.local/share/virtualenvs/eopf-cpm-gah88zwo/lib/python3.9/site-packages/zarr/hierarchy.py", line 821, in create_dataset

    return self._write_op(self._create_dataset_nosync, name, **kwargs)

  File "/home/gbeaucha/.local/share/virtualenvs/eopf-cpm-gah88zwo/lib/python3.9/site-packages/zarr/hierarchy.py", line 673, in _write_op

    return f(*args, **kwargs)

  File "/home/gbeaucha/.local/share/virtualenvs/eopf-cpm-gah88zwo/lib/python3.9/site-packages/zarr/hierarchy.py", line 834, in _create_dataset_nosync

    a = create(store=self._store, path=path, chunk_store=self._chunk_store,

  File "/home/gbeaucha/.local/share/virtualenvs/eopf-cpm-gah88zwo/lib/python3.9/site-packages/zarr/creation.py", line 149, in create

    init_array(store, shape=shape, chunks=chunks, dtype=dtype, compressor=compressor,

  File "/home/gbeaucha/.local/share/virtualenvs/eopf-cpm-gah88zwo/lib/python3.9/site-packages/zarr/storage.py", line 351, in init_array

    _init_array_metadata(store, shape=shape, chunks=chunks, dtype=dtype,

  File "/home/gbeaucha/.local/share/virtualenvs/eopf-cpm-gah88zwo/lib/python3.9/site-packages/zarr/storage.py", line 450, in _init_array_metadata

    store[key] = store._metadata_class.encode_array_metadata(meta)  # type: ignore

  File "/home/gbeaucha/.local/share/virtualenvs/eopf-cpm-gah88zwo/lib/python3.9/site-packages/zarr/meta.py", line 102, in encode_array_metadata

    return json_dumps(meta)

  File "/home/gbeaucha/.local/share/virtualenvs/eopf-cpm-gah88zwo/lib/python3.9/site-packages/zarr/util.py", line 38, in json_dumps

    return json.dumps(o, indent=4, sort_keys=True, ensure_ascii=True,

  File "/usr/lib/python3.9/json/__init__.py", line 234, in dumps

    return cls(

  File "/usr/lib/python3.9/json/encoder.py", line 201, in encode

    chunks = list(chunks)

  File "/usr/lib/python3.9/json/encoder.py", line 431, in _iterencode

    yield from _iterencode_dict(o, _current_indent_level)

  File "/usr/lib/python3.9/json/encoder.py", line 405, in _iterencode_dict

    yield from chunks

  File "/usr/lib/python3.9/json/encoder.py", line 438, in _iterencode

    o = _default(o)

  File "/usr/lib/python3.9/json/encoder.py", line 179, in default

    raise TypeError(f'Object of type {o.__class__.__name__} '

TypeError: Object of type bytes is not JSON serializable



Exited all contexts

double free or corruption (out)

Abandon
```

### File header 

<details> 
  <summary>spoiler : viscal file header</summary>

```
netcdf viscal {
dimensions:
	integrators = 2 ;
	one = 1 ;
	swir_detectors = 8 ;
	views = 2 ;
	visible_detectors = 4 ;
variables:
	string ANX_time(one) ;
		ANX_time:long_name = "Time of ascending node crossing in the UTC YYYY-MM-DDThh:mm:ss.ddddddZ CCSDS format" ;
		ANX_time:standard_name = "time" ;
	float S1_BB1_SD(visible_detectors, views, integrators) ;
		S1_BB1_SD:_FillValue = NaNf ;
		S1_BB1_SD:long_name = "555nm BB1 noise counts" ;
	float S1_BB1_means(visible_detectors, views, integrators) ;
		S1_BB1_means:_FillValue = NaNf ;
		S1_BB1_means:long_name = "555nm BB1 average counts" ;
	float S1_VISCAL_SD(visible_detectors, views, integrators) ;
		S1_VISCAL_SD:_FillValue = NaNf ;
		S1_VISCAL_SD:long_name = "555nm VISCAL noise counts" ;
	float S1_VISCAL_means(visible_detectors, views, integrators) ;
		S1_VISCAL_means:_FillValue = NaNf ;
		S1_VISCAL_means:long_name = "555nm VISCAL average counts" ;
	float S1_slopes(visible_detectors, views, integrators) ;
		S1_slopes:_FillValue = NaNf ;
		S1_slopes:long_name = "555nm slopes" ;
	float S1_solar_irradiances(visible_detectors, views) ;
		S1_solar_irradiances:_FillValue = NaNf ;
		S1_solar_irradiances:long_name = "555nm solar irradiances" ;
		S1_solar_irradiances:units = "mW m-2 nm-1" ;
	float S2_BB1_SD(visible_detectors, views, integrators) ;
		S2_BB1_SD:_FillValue = NaNf ;
		S2_BB1_SD:long_name = "659nm BB1 noise counts" ;
	float S2_BB1_means(visible_detectors, views, integrators) ;
		S2_BB1_means:_FillValue = NaNf ;
		S2_BB1_means:long_name = "659nm BB1 average counts" ;
	float S2_VISCAL_SD(visible_detectors, views, integrators) ;
		S2_VISCAL_SD:_FillValue = NaNf ;
		S2_VISCAL_SD:long_name = "659nm VISCAL noise counts" ;
	float S2_VISCAL_means(visible_detectors, views, integrators) ;
		S2_VISCAL_means:_FillValue = NaNf ;
		S2_VISCAL_means:long_name = "659nm VISCAL average counts" ;
	float S2_slopes(visible_detectors, views, integrators) ;
		S2_slopes:_FillValue = NaNf ;
		S2_slopes:long_name = "659nm slopes" ;
	float S2_solar_irradiances(visible_detectors, views) ;
		S2_solar_irradiances:_FillValue = NaNf ;
		S2_solar_irradiances:long_name = "659nm solar irradiances" ;
		S2_solar_irradiances:units = "mW m-2 nm-1" ;
	float S3_BB1_SD(visible_detectors, views, integrators) ;
		S3_BB1_SD:_FillValue = NaNf ;
		S3_BB1_SD:long_name = "865nm BB1 noise counts" ;
	float S3_BB1_means(visible_detectors, views, integrators) ;
		S3_BB1_means:_FillValue = NaNf ;
		S3_BB1_means:long_name = "865nm BB1 average counts" ;
	float S3_VISCAL_SD(visible_detectors, views, integrators) ;
		S3_VISCAL_SD:_FillValue = NaNf ;
		S3_VISCAL_SD:long_name = "865nm VISCAL noise counts" ;
	float S3_VISCAL_means(visible_detectors, views, integrators) ;
		S3_VISCAL_means:_FillValue = NaNf ;
		S3_VISCAL_means:long_name = "865nm VISCAL average counts" ;
	float S3_slopes(visible_detectors, views, integrators) ;
		S3_slopes:_FillValue = NaNf ;
		S3_slopes:long_name = "865nm slopes" ;
	float S3_solar_irradiances(visible_detectors, views) ;
		S3_solar_irradiances:_FillValue = NaNf ;
		S3_solar_irradiances:long_name = "865nm solar irradiances" ;
		S3_solar_irradiances:units = "mW m-2 nm-1" ;
	float S4_BB1_SD(swir_detectors, views, integrators) ;
		S4_BB1_SD:_FillValue = NaNf ;
		S4_BB1_SD:long_name = "1.375microm BB1 noise counts" ;
	float S4_BB1_means(swir_detectors, views, integrators) ;
		S4_BB1_means:_FillValue = NaNf ;
		S4_BB1_means:long_name = "1.375microm BB1 average counts" ;
	float S4_VISCAL_SD(swir_detectors, views, integrators) ;
		S4_VISCAL_SD:_FillValue = NaNf ;
		S4_VISCAL_SD:long_name = "1.375microm VISCAL noise counts" ;
	float S4_VISCAL_means(swir_detectors, views, integrators) ;
		S4_VISCAL_means:_FillValue = NaNf ;
		S4_VISCAL_means:long_name = "1.375microm VISCAL average counts" ;
	float S4_slopes(swir_detectors, views, integrators) ;
		S4_slopes:_FillValue = NaNf ;
		S4_slopes:long_name = "1.375microm slopes" ;
	float S4_solar_irradiances(swir_detectors, views) ;
		S4_solar_irradiances:_FillValue = NaNf ;
		S4_solar_irradiances:long_name = "1.375microm solar irradiances" ;
		S4_solar_irradiances:units = "mW m-2 nm-1" ;
	float S5_BB1_SD(swir_detectors, views, integrators) ;
		S5_BB1_SD:_FillValue = NaNf ;
		S5_BB1_SD:long_name = "1.61microm BB1 noise counts" ;
	float S5_BB1_means(swir_detectors, views, integrators) ;
		S5_BB1_means:_FillValue = NaNf ;
		S5_BB1_means:long_name = "1.61microm BB1 average counts" ;
	float S5_VISCAL_SD(swir_detectors, views, integrators) ;
		S5_VISCAL_SD:_FillValue = NaNf ;
		S5_VISCAL_SD:long_name = "1.61microm VISCAL noise counts" ;
	float S5_VISCAL_means(swir_detectors, views, integrators) ;
		S5_VISCAL_means:_FillValue = NaNf ;
		S5_VISCAL_means:long_name = "1.61microm VISCAL average counts" ;
	float S5_slopes(swir_detectors, views, integrators) ;
		S5_slopes:_FillValue = NaNf ;
		S5_slopes:long_name = "1.61microm slopes" ;
	float S5_solar_irradiances(swir_detectors, views) ;
		S5_solar_irradiances:_FillValue = NaNf ;
		S5_solar_irradiances:long_name = "1.61microm solar irradiances" ;
		S5_solar_irradiances:units = "mW m-2 nm-1" ;
	float S6_BB1_SD(swir_detectors, views, integrators) ;
		S6_BB1_SD:_FillValue = NaNf ;
		S6_BB1_SD:long_name = "2.25microm BB1 noise counts" ;
	float S6_BB1_means(swir_detectors, views, integrators) ;
		S6_BB1_means:_FillValue = NaNf ;
		S6_BB1_means:long_name = "2.25microm BB1 average counts" ;
	float S6_VISCAL_SD(swir_detectors, views, integrators) ;
		S6_VISCAL_SD:_FillValue = NaNf ;
		S6_VISCAL_SD:long_name = "2.25microm VISCAL noise counts" ;
	float S6_VISCAL_means(swir_detectors, views, integrators) ;
		S6_VISCAL_means:_FillValue = NaNf ;
		S6_VISCAL_means:long_name = "2.25microm VISCAL average counts" ;
	float S6_slopes(swir_detectors, views, integrators) ;
		S6_slopes:_FillValue = NaNf ;
		S6_slopes:long_name = "2.25microm slopes" ;
	float S6_solar_irradiances(swir_detectors, views) ;
		S6_solar_irradiances:_FillValue = NaNf ;
		S6_solar_irradiances:long_name = "2.25microm solar irradiances" ;
		S6_solar_irradiances:units = "mW m-2 nm-1" ;
	string calibration_time(one) ;
		calibration_time:long_name = "Time of calibration in the UTC YYYY-MM-DDThh:mm:ss.ddddddZ CCSDS format" ;
		calibration_time:standard_name = "time" ;
	float monitor_SD(one) ;
		monitor_SD:_FillValue = NaNf ;
		monitor_SD:long_name = "Monitor diode noise counts" ;
	float monitor_mean(one) ;
		monitor_mean:_FillValue = NaNf ;
		monitor_mean:long_name = "Monitor diode average counts" ;

// global attributes:
		:contact = "eosupport@copernicus.esa.int" ;
		:creation_time = "20220605T083021Z" ;
		:history = "  2022-06-05T08:30:21Z: PUGCoreProcessor joborder.19812183.xml" ;
		:institution = "PS1" ;
		:netCDF_version = "4.2 of Mar 13 2018 10:14:33 $" ;
		:processing_baseline = "SL__L1_.004.04.00" ;
		:product_name = "S3A_SL_1_RBT____20220603T234543_20220603T234843_20220605T083021_0179_086_087_3780_PS1_O_NT_004.SEN3" ;
		:references = "" ;
		:source = "IPF-SL-1 06.19" ;
		:title = "S3 SLSTR L1 Radiance and Brightness Temperatures Product. (Measurements + Annotations)" ;
}

```
</details>

### Versions used
kerchunk version: 0.0.6
fsspec version: 2022.3.0

**Comment by gbfree** [comment]
I assume it either segfault when the fsspec file is closed or if we got "lucky" later double free when it get garbage collected.

**Comment by martindurant** [comment]
We definitely need some work around object encoding in HDF5, this has come up a few times in issues and even partial PRs. At the very least, `_translator` should never be allowed to pass exceptions up the stack, since it seems HDF5 can't handle this cleanly: a warning should be raised.

**Comment by gbfree** [comment]
With your branch both my exemple and full application no longer raise an exception, warning nor segfault.
