### ISSUE TITLE
LazyReferenceMapper error when pointing to s3

### ISSUE THREAD

**Issue by maxrjones** [fsspec/kerchunk#412]
I'm having some difficulty fixing the [Parquet storage guide](https://projectpythia.org/kerchunk-cookbook/notebooks/advanced/Parquet_Reference_Storage.html) in the Kerchunk Pythia cookbook and would appreciate any guidance. I updated the syntax for https://github.com/fsspec/filesystem_spec/pull/1420, but am still getting an error when combining references. The individual in-memory references work.

MVCE:

```Python
import os

import fsspec
import xarray as xr
from fsspec.implementations.reference import LazyReferenceMapper
from kerchunk.combine import MultiZarrToZarr
from kerchunk.hdf import SingleHdf5ToZarr

# Initiate fsspec filesystems for reading
fs_read = fsspec.filesystem("s3", anon=True, skip_instance_cache=True)

files_paths = fs_read.glob("s3://smn-ar-wrf/DATA/WRF/DET/2022/12/31/12/*")

# Here we prepend the prefix 's3://', which points to AWS.
file_pattern = sorted(["s3://" + f for f in files_paths])

# Grab the first seven files to speed up example.
file_pattern = file_pattern[0:2]

# Use Kerchunk's `SingleHdf5ToZarr` method to create a `Kerchunk`
# index from a NetCDF file.
fs_read = fsspec.filesystem("s3", anon=True, skip_instance_cache=True)
so = dict(mode="rb", anon=True, default_fill_cache=False, default_cache_type="first")

def generate_json_reference(fil):
    with fs_read.open(fil, **so) as infile:
        h5chunks = SingleHdf5ToZarr(infile, fil, inline_threshold=1000)
        return h5chunks.translate()  # outf

# Generate Dask Delayed objects
single_refs = [(generate_json_reference)(fil) for fil in file_pattern]
fs = fsspec.filesystem("file")

os.makedirs("combined.parq")

out = LazyReferenceMapper.create(root="combined.parq", fs=fs, record_size=2)

mzz = MultiZarrToZarr(
    single_refs,
    remote_protocol="memory",
    concat_dims=["time"],
    identical_dims=["y", "x"],
    out=out,
).translate()

out.flush()
```

Traceback:
```Python
(kerchunk) Maxs-MacBook-Pro:.vscode max$ python parquet-test.py 
Traceback (most recent call last):
  File "/Users/max/CarbonPlan Dropbox/Max Jones/Documents/Code/fsspec/kerchunk/.vscode/parquet-test.py", line 45, in <module>
    ).translate()
  File "/Users/max/CarbonPlan Dropbox/Max Jones/Documents/Code/fsspec/kerchunk/kerchunk/combine.py", line 501, in translate
    self.first_pass()
  File "/Users/max/CarbonPlan Dropbox/Max Jones/Documents/Code/fsspec/kerchunk/kerchunk/combine.py", line 258, in first_pass
    value = self._get_value(i, z, var, fn=self._paths[i])
  File "/Users/max/CarbonPlan Dropbox/Max Jones/Documents/Code/fsspec/kerchunk/kerchunk/combine.py", line 226, in _get_value
    o = z[selector.split(":", 1)[1]][...]
  File "/Users/max/mambaforge/envs/kerchunk/lib/python3.10/site-packages/zarr/core.py", line 844, in __getitem__
    result = self.get_basic_selection(pure_selection, fields=fields)
  File "/Users/max/mambaforge/envs/kerchunk/lib/python3.10/site-packages/zarr/core.py", line 970, in get_basic_selection
    return self._get_basic_selection_nd(selection=selection, out=out, fields=fields)
  File "/Users/max/mambaforge/envs/kerchunk/lib/python3.10/site-packages/zarr/core.py", line 1012, in _get_basic_selection_nd
    return self._get_selection(indexer=indexer, out=out, fields=fields)
  File "/Users/max/mambaforge/envs/kerchunk/lib/python3.10/site-packages/zarr/core.py", line 1388, in _get_selection
    self._chunk_getitems(
  File "/Users/max/mambaforge/envs/kerchunk/lib/python3.10/site-packages/zarr/core.py", line 2224, in _chunk_getitems
    cdatas = self.chunk_store.getitems(ckeys, contexts=contexts)
  File "/Users/max/mambaforge/envs/kerchunk/lib/python3.10/site-packages/zarr/storage.py", line 1420, in getitems
    results = self.map.getitems(keys_transformed, on_error="omit")
  File "/Users/max/mambaforge/envs/kerchunk/lib/python3.10/site-packages/fsspec/mapping.py", line 101, in getitems
    out = self.fs.cat(keys2, on_error=oe)
  File "/Users/max/mambaforge/envs/kerchunk/lib/python3.10/site-packages/fsspec/implementations/reference.py", line 829, in cat
    fs = self.fss[proto]
KeyError: 's3'
```

**Comment by martindurant** [comment]
```
mzz = MultiZarrToZarr(
    single_refs,
    remote_protocol="memory",
    concat_dims=["time"],
    identical_dims=["y", "x"],
    out=out,
).translate()
```
Remote protocol is "s3", and you should include something like `remote_options={"anon": True}` as before.

**Comment by maxrjones** [comment]
> ```
> mzz = MultiZarrToZarr(
>     single_refs,
>     remote_protocol="memory",
>     concat_dims=["time"],
>     identical_dims=["y", "x"],
>     out=out,
> ).translate()
> ```
> 
> Remote protocol is "s3", and you should include something like `remote_options={"anon": True}` as before.

Thank you!
